// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

/**
 * Protobuf type {@code blockchain.AppendRecordRequest}
 */
public  final class AppendRecordRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.AppendRecordRequest)
    AppendRecordRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppendRecordRequest.newBuilder() to construct.
  private AppendRecordRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppendRecordRequest() {
    apiKey_ = "";
    assetId_ = "";
    recordName_ = "";
    content_ = "";
    metaHash_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppendRecordRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            apiKey_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assetId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            recordName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            metaHash_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AppendRecordRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AppendRecordRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.launch.diagdevice.blockchain.AppendRecordRequest.class, com.launch.diagdevice.blockchain.AppendRecordRequest.Builder.class);
  }

  public static final int API_KEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object apiKey_;
  /**
   * <code>string api_key = 1;</code>
   */
  public java.lang.String getApiKey() {
    java.lang.Object ref = apiKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apiKey_ = s;
      return s;
    }
  }
  /**
   * <code>string api_key = 1;</code>
   */
  public com.google.protobuf.ByteString
      getApiKeyBytes() {
    java.lang.Object ref = apiKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apiKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object assetId_;
  /**
   * <pre>
   * 资产ID
   * </pre>
   *
   * <code>string asset_id = 2;</code>
   */
  public java.lang.String getAssetId() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资产ID
   * </pre>
   *
   * <code>string asset_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssetIdBytes() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORD_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object recordName_;
  /**
   * <pre>
   * 记录名称
   * </pre>
   *
   * <code>string record_name = 3;</code>
   */
  public java.lang.String getRecordName() {
    java.lang.Object ref = recordName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 记录名称
   * </pre>
   *
   * <code>string record_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRecordNameBytes() {
    java.lang.Object ref = recordName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object content_;
  /**
   * <pre>
   * 记录内容
   * </pre>
   *
   * <code>string content = 4;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 记录内容
   * </pre>
   *
   * <code>string content = 4;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int META_HASH_FIELD_NUMBER = 5;
  private volatile java.lang.Object metaHash_;
  /**
   * <pre>
   * 记录的哈希值
   * </pre>
   *
   * <code>string meta_hash = 5;</code>
   */
  public java.lang.String getMetaHash() {
    java.lang.Object ref = metaHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metaHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 记录的哈希值
   * </pre>
   *
   * <code>string meta_hash = 5;</code>
   */
  public com.google.protobuf.ByteString
      getMetaHashBytes() {
    java.lang.Object ref = metaHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metaHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getApiKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apiKey_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assetId_);
    }
    if (!getRecordNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recordName_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
    }
    if (!getMetaHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, metaHash_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getApiKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apiKey_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assetId_);
    }
    if (!getRecordNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recordName_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
    }
    if (!getMetaHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, metaHash_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.launch.diagdevice.blockchain.AppendRecordRequest)) {
      return super.equals(obj);
    }
    com.launch.diagdevice.blockchain.AppendRecordRequest other = (com.launch.diagdevice.blockchain.AppendRecordRequest) obj;

    boolean result = true;
    result = result && getApiKey()
        .equals(other.getApiKey());
    result = result && getAssetId()
        .equals(other.getAssetId());
    result = result && getRecordName()
        .equals(other.getRecordName());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getMetaHash()
        .equals(other.getMetaHash());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + API_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getApiKey().hashCode();
    hash = (37 * hash) + ASSET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAssetId().hashCode();
    hash = (37 * hash) + RECORD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRecordName().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + META_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getMetaHash().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AppendRecordRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.launch.diagdevice.blockchain.AppendRecordRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.AppendRecordRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.AppendRecordRequest)
      com.launch.diagdevice.blockchain.AppendRecordRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AppendRecordRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AppendRecordRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.launch.diagdevice.blockchain.AppendRecordRequest.class, com.launch.diagdevice.blockchain.AppendRecordRequest.Builder.class);
    }

    // Construct using com.launch.diagdevice.blockchain.AppendRecordRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      apiKey_ = "";

      assetId_ = "";

      recordName_ = "";

      content_ = "";

      metaHash_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AppendRecordRequest_descriptor;
    }

    public com.launch.diagdevice.blockchain.AppendRecordRequest getDefaultInstanceForType() {
      return com.launch.diagdevice.blockchain.AppendRecordRequest.getDefaultInstance();
    }

    public com.launch.diagdevice.blockchain.AppendRecordRequest build() {
      com.launch.diagdevice.blockchain.AppendRecordRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.launch.diagdevice.blockchain.AppendRecordRequest buildPartial() {
      com.launch.diagdevice.blockchain.AppendRecordRequest result = new com.launch.diagdevice.blockchain.AppendRecordRequest(this);
      result.apiKey_ = apiKey_;
      result.assetId_ = assetId_;
      result.recordName_ = recordName_;
      result.content_ = content_;
      result.metaHash_ = metaHash_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.launch.diagdevice.blockchain.AppendRecordRequest) {
        return mergeFrom((com.launch.diagdevice.blockchain.AppendRecordRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.launch.diagdevice.blockchain.AppendRecordRequest other) {
      if (other == com.launch.diagdevice.blockchain.AppendRecordRequest.getDefaultInstance()) return this;
      if (!other.getApiKey().isEmpty()) {
        apiKey_ = other.apiKey_;
        onChanged();
      }
      if (!other.getAssetId().isEmpty()) {
        assetId_ = other.assetId_;
        onChanged();
      }
      if (!other.getRecordName().isEmpty()) {
        recordName_ = other.recordName_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getMetaHash().isEmpty()) {
        metaHash_ = other.metaHash_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.launch.diagdevice.blockchain.AppendRecordRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.launch.diagdevice.blockchain.AppendRecordRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object apiKey_ = "";
    /**
     * <code>string api_key = 1;</code>
     */
    public java.lang.String getApiKey() {
      java.lang.Object ref = apiKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string api_key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApiKeyBytes() {
      java.lang.Object ref = apiKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string api_key = 1;</code>
     */
    public Builder setApiKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      apiKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string api_key = 1;</code>
     */
    public Builder clearApiKey() {
      
      apiKey_ = getDefaultInstance().getApiKey();
      onChanged();
      return this;
    }
    /**
     * <code>string api_key = 1;</code>
     */
    public Builder setApiKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      apiKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetId_ = "";
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public java.lang.String getAssetId() {
      java.lang.Object ref = assetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = assetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public Builder setAssetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public Builder clearAssetId() {
      
      assetId_ = getDefaultInstance().getAssetId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public Builder setAssetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recordName_ = "";
    /**
     * <pre>
     * 记录名称
     * </pre>
     *
     * <code>string record_name = 3;</code>
     */
    public java.lang.String getRecordName() {
      java.lang.Object ref = recordName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 记录名称
     * </pre>
     *
     * <code>string record_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRecordNameBytes() {
      java.lang.Object ref = recordName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 记录名称
     * </pre>
     *
     * <code>string record_name = 3;</code>
     */
    public Builder setRecordName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recordName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 记录名称
     * </pre>
     *
     * <code>string record_name = 3;</code>
     */
    public Builder clearRecordName() {
      
      recordName_ = getDefaultInstance().getRecordName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 记录名称
     * </pre>
     *
     * <code>string record_name = 3;</code>
     */
    public Builder setRecordNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recordName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * 记录内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 记录内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 记录内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 记录内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 记录内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object metaHash_ = "";
    /**
     * <pre>
     * 记录的哈希值
     * </pre>
     *
     * <code>string meta_hash = 5;</code>
     */
    public java.lang.String getMetaHash() {
      java.lang.Object ref = metaHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metaHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 记录的哈希值
     * </pre>
     *
     * <code>string meta_hash = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMetaHashBytes() {
      java.lang.Object ref = metaHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metaHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 记录的哈希值
     * </pre>
     *
     * <code>string meta_hash = 5;</code>
     */
    public Builder setMetaHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metaHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 记录的哈希值
     * </pre>
     *
     * <code>string meta_hash = 5;</code>
     */
    public Builder clearMetaHash() {
      
      metaHash_ = getDefaultInstance().getMetaHash();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 记录的哈希值
     * </pre>
     *
     * <code>string meta_hash = 5;</code>
     */
    public Builder setMetaHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metaHash_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.AppendRecordRequest)
  }

  // @@protoc_insertion_point(class_scope:blockchain.AppendRecordRequest)
  private static final com.launch.diagdevice.blockchain.AppendRecordRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.launch.diagdevice.blockchain.AppendRecordRequest();
  }

  public static com.launch.diagdevice.blockchain.AppendRecordRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendRecordRequest>
      PARSER = new com.google.protobuf.AbstractParser<AppendRecordRequest>() {
    public AppendRecordRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppendRecordRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppendRecordRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendRecordRequest> getParserForType() {
    return PARSER;
  }

  public com.launch.diagdevice.blockchain.AppendRecordRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

