// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

public interface AssetRecordCountReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.AssetRecordCountReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 资产中记录的数量, 十进制字符串
   * </pre>
   *
   * <code>string record_count = 1;</code>
   */
  java.lang.String getRecordCount();
  /**
   * <pre>
   * 资产中记录的数量, 十进制字符串
   * </pre>
   *
   * <code>string record_count = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecordCountBytes();
}
