// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

/**
 * Protobuf type {@code blockchain.AssetReply}
 */
public  final class AssetReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.AssetReply)
    AssetReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssetReply.newBuilder() to construct.
  private AssetReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssetReply() {
    addressOwner_ = "";
    assetId_ = "";
    assetName_ = "";
    assetContent_ = "";
    assetHash_ = "";
    status_ = 0;
    createTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AssetReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            addressOwner_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assetId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            assetName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            assetContent_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            assetHash_ = s;
            break;
          }
          case 48: {

            status_ = input.readUInt32();
            break;
          }
          case 56: {

            createTime_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.launch.diagdevice.blockchain.AssetReply.class, com.launch.diagdevice.blockchain.AssetReply.Builder.class);
  }

  public static final int ADDRESS_OWNER_FIELD_NUMBER = 1;
  private volatile java.lang.Object addressOwner_;
  /**
   * <pre>
   * 资产所属人账号地址
   * </pre>
   *
   * <code>string address_owner = 1;</code>
   */
  public java.lang.String getAddressOwner() {
    java.lang.Object ref = addressOwner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addressOwner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资产所属人账号地址
   * </pre>
   *
   * <code>string address_owner = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAddressOwnerBytes() {
    java.lang.Object ref = addressOwner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addressOwner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object assetId_;
  /**
   * <pre>
   * 资产ID
   * </pre>
   *
   * <code>string asset_id = 2;</code>
   */
  public java.lang.String getAssetId() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资产ID
   * </pre>
   *
   * <code>string asset_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssetIdBytes() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object assetName_;
  /**
   * <pre>
   * 资产名称
   * </pre>
   *
   * <code>string asset_name = 3;</code>
   */
  public java.lang.String getAssetName() {
    java.lang.Object ref = assetName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资产名称
   * </pre>
   *
   * <code>string asset_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAssetNameBytes() {
    java.lang.Object ref = assetName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_CONTENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object assetContent_;
  /**
   * <pre>
   * 附加内容
   * </pre>
   *
   * <code>string asset_content = 4;</code>
   */
  public java.lang.String getAssetContent() {
    java.lang.Object ref = assetContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 附加内容
   * </pre>
   *
   * <code>string asset_content = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAssetContentBytes() {
    java.lang.Object ref = assetContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_HASH_FIELD_NUMBER = 5;
  private volatile java.lang.Object assetHash_;
  /**
   * <pre>
   * 资产 Hash
   * </pre>
   *
   * <code>string asset_hash = 5;</code>
   */
  public java.lang.String getAssetHash() {
    java.lang.Object ref = assetHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资产 Hash
   * </pre>
   *
   * <code>string asset_hash = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAssetHashBytes() {
    java.lang.Object ref = assetHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_;
  /**
   * <pre>
   * 资产状态
   * </pre>
   *
   * <code>uint32 status = 6;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 7;
  private long createTime_;
  /**
   * <pre>
   * 资产创建时间, Unix 时间
   * </pre>
   *
   * <code>uint64 create_time = 7;</code>
   */
  public long getCreateTime() {
    return createTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAddressOwnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressOwner_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assetId_);
    }
    if (!getAssetNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, assetName_);
    }
    if (!getAssetContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, assetContent_);
    }
    if (!getAssetHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, assetHash_);
    }
    if (status_ != 0) {
      output.writeUInt32(6, status_);
    }
    if (createTime_ != 0L) {
      output.writeUInt64(7, createTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAddressOwnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressOwner_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assetId_);
    }
    if (!getAssetNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, assetName_);
    }
    if (!getAssetContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, assetContent_);
    }
    if (!getAssetHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, assetHash_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, status_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, createTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.launch.diagdevice.blockchain.AssetReply)) {
      return super.equals(obj);
    }
    com.launch.diagdevice.blockchain.AssetReply other = (com.launch.diagdevice.blockchain.AssetReply) obj;

    boolean result = true;
    result = result && getAddressOwner()
        .equals(other.getAddressOwner());
    result = result && getAssetId()
        .equals(other.getAssetId());
    result = result && getAssetName()
        .equals(other.getAssetName());
    result = result && getAssetContent()
        .equals(other.getAssetContent());
    result = result && getAssetHash()
        .equals(other.getAssetHash());
    result = result && (getStatus()
        == other.getStatus());
    result = result && (getCreateTime()
        == other.getCreateTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getAddressOwner().hashCode();
    hash = (37 * hash) + ASSET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAssetId().hashCode();
    hash = (37 * hash) + ASSET_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAssetName().hashCode();
    hash = (37 * hash) + ASSET_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getAssetContent().hashCode();
    hash = (37 * hash) + ASSET_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getAssetHash().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AssetReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.launch.diagdevice.blockchain.AssetReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.AssetReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.AssetReply)
      com.launch.diagdevice.blockchain.AssetReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.launch.diagdevice.blockchain.AssetReply.class, com.launch.diagdevice.blockchain.AssetReply.Builder.class);
    }

    // Construct using com.launch.diagdevice.blockchain.AssetReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      addressOwner_ = "";

      assetId_ = "";

      assetName_ = "";

      assetContent_ = "";

      assetHash_ = "";

      status_ = 0;

      createTime_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetReply_descriptor;
    }

    public com.launch.diagdevice.blockchain.AssetReply getDefaultInstanceForType() {
      return com.launch.diagdevice.blockchain.AssetReply.getDefaultInstance();
    }

    public com.launch.diagdevice.blockchain.AssetReply build() {
      com.launch.diagdevice.blockchain.AssetReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.launch.diagdevice.blockchain.AssetReply buildPartial() {
      com.launch.diagdevice.blockchain.AssetReply result = new com.launch.diagdevice.blockchain.AssetReply(this);
      result.addressOwner_ = addressOwner_;
      result.assetId_ = assetId_;
      result.assetName_ = assetName_;
      result.assetContent_ = assetContent_;
      result.assetHash_ = assetHash_;
      result.status_ = status_;
      result.createTime_ = createTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.launch.diagdevice.blockchain.AssetReply) {
        return mergeFrom((com.launch.diagdevice.blockchain.AssetReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.launch.diagdevice.blockchain.AssetReply other) {
      if (other == com.launch.diagdevice.blockchain.AssetReply.getDefaultInstance()) return this;
      if (!other.getAddressOwner().isEmpty()) {
        addressOwner_ = other.addressOwner_;
        onChanged();
      }
      if (!other.getAssetId().isEmpty()) {
        assetId_ = other.assetId_;
        onChanged();
      }
      if (!other.getAssetName().isEmpty()) {
        assetName_ = other.assetName_;
        onChanged();
      }
      if (!other.getAssetContent().isEmpty()) {
        assetContent_ = other.assetContent_;
        onChanged();
      }
      if (!other.getAssetHash().isEmpty()) {
        assetHash_ = other.assetHash_;
        onChanged();
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.launch.diagdevice.blockchain.AssetReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.launch.diagdevice.blockchain.AssetReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object addressOwner_ = "";
    /**
     * <pre>
     * 资产所属人账号地址
     * </pre>
     *
     * <code>string address_owner = 1;</code>
     */
    public java.lang.String getAddressOwner() {
      java.lang.Object ref = addressOwner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressOwner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资产所属人账号地址
     * </pre>
     *
     * <code>string address_owner = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressOwnerBytes() {
      java.lang.Object ref = addressOwner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资产所属人账号地址
     * </pre>
     *
     * <code>string address_owner = 1;</code>
     */
    public Builder setAddressOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addressOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产所属人账号地址
     * </pre>
     *
     * <code>string address_owner = 1;</code>
     */
    public Builder clearAddressOwner() {
      
      addressOwner_ = getDefaultInstance().getAddressOwner();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产所属人账号地址
     * </pre>
     *
     * <code>string address_owner = 1;</code>
     */
    public Builder setAddressOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addressOwner_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetId_ = "";
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public java.lang.String getAssetId() {
      java.lang.Object ref = assetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = assetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public Builder setAssetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public Builder clearAssetId() {
      
      assetId_ = getDefaultInstance().getAssetId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产ID
     * </pre>
     *
     * <code>string asset_id = 2;</code>
     */
    public Builder setAssetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetName_ = "";
    /**
     * <pre>
     * 资产名称
     * </pre>
     *
     * <code>string asset_name = 3;</code>
     */
    public java.lang.String getAssetName() {
      java.lang.Object ref = assetName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资产名称
     * </pre>
     *
     * <code>string asset_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAssetNameBytes() {
      java.lang.Object ref = assetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资产名称
     * </pre>
     *
     * <code>string asset_name = 3;</code>
     */
    public Builder setAssetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产名称
     * </pre>
     *
     * <code>string asset_name = 3;</code>
     */
    public Builder clearAssetName() {
      
      assetName_ = getDefaultInstance().getAssetName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产名称
     * </pre>
     *
     * <code>string asset_name = 3;</code>
     */
    public Builder setAssetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetContent_ = "";
    /**
     * <pre>
     * 附加内容
     * </pre>
     *
     * <code>string asset_content = 4;</code>
     */
    public java.lang.String getAssetContent() {
      java.lang.Object ref = assetContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 附加内容
     * </pre>
     *
     * <code>string asset_content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAssetContentBytes() {
      java.lang.Object ref = assetContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 附加内容
     * </pre>
     *
     * <code>string asset_content = 4;</code>
     */
    public Builder setAssetContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 附加内容
     * </pre>
     *
     * <code>string asset_content = 4;</code>
     */
    public Builder clearAssetContent() {
      
      assetContent_ = getDefaultInstance().getAssetContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 附加内容
     * </pre>
     *
     * <code>string asset_content = 4;</code>
     */
    public Builder setAssetContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetContent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetHash_ = "";
    /**
     * <pre>
     * 资产 Hash
     * </pre>
     *
     * <code>string asset_hash = 5;</code>
     */
    public java.lang.String getAssetHash() {
      java.lang.Object ref = assetHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资产 Hash
     * </pre>
     *
     * <code>string asset_hash = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAssetHashBytes() {
      java.lang.Object ref = assetHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资产 Hash
     * </pre>
     *
     * <code>string asset_hash = 5;</code>
     */
    public Builder setAssetHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产 Hash
     * </pre>
     *
     * <code>string asset_hash = 5;</code>
     */
    public Builder clearAssetHash() {
      
      assetHash_ = getDefaultInstance().getAssetHash();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产 Hash
     * </pre>
     *
     * <code>string asset_hash = 5;</code>
     */
    public Builder setAssetHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetHash_ = value;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <pre>
     * 资产状态
     * </pre>
     *
     * <code>uint32 status = 6;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     * 资产状态
     * </pre>
     *
     * <code>uint32 status = 6;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产状态
     * </pre>
     *
     * <code>uint32 status = 6;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     * 资产创建时间, Unix 时间
     * </pre>
     *
     * <code>uint64 create_time = 7;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     * 资产创建时间, Unix 时间
     * </pre>
     *
     * <code>uint64 create_time = 7;</code>
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产创建时间, Unix 时间
     * </pre>
     *
     * <code>uint64 create_time = 7;</code>
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.AssetReply)
  }

  // @@protoc_insertion_point(class_scope:blockchain.AssetReply)
  private static final com.launch.diagdevice.blockchain.AssetReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.launch.diagdevice.blockchain.AssetReply();
  }

  public static com.launch.diagdevice.blockchain.AssetReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetReply>
      PARSER = new com.google.protobuf.AbstractParser<AssetReply>() {
    public AssetReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AssetReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AssetReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetReply> getParserForType() {
    return PARSER;
  }

  public com.launch.diagdevice.blockchain.AssetReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

