// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

public interface AssetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.AssetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 资产所属人账号地址
   * </pre>
   *
   * <code>string address_owner = 1;</code>
   */
  java.lang.String getAddressOwner();
  /**
   * <pre>
   * 资产所属人账号地址
   * </pre>
   *
   * <code>string address_owner = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressOwnerBytes();

  /**
   * <pre>
   * 资产ID
   * </pre>
   *
   * <code>string asset_id = 2;</code>
   */
  java.lang.String getAssetId();
  /**
   * <pre>
   * 资产ID
   * </pre>
   *
   * <code>string asset_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <pre>
   * 资产名称
   * </pre>
   *
   * <code>string asset_name = 3;</code>
   */
  java.lang.String getAssetName();
  /**
   * <pre>
   * 资产名称
   * </pre>
   *
   * <code>string asset_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getAssetNameBytes();

  /**
   * <pre>
   * 附加内容
   * </pre>
   *
   * <code>string asset_content = 4;</code>
   */
  java.lang.String getAssetContent();
  /**
   * <pre>
   * 附加内容
   * </pre>
   *
   * <code>string asset_content = 4;</code>
   */
  com.google.protobuf.ByteString
      getAssetContentBytes();

  /**
   * <pre>
   * 资产 Hash
   * </pre>
   *
   * <code>string asset_hash = 5;</code>
   */
  java.lang.String getAssetHash();
  /**
   * <pre>
   * 资产 Hash
   * </pre>
   *
   * <code>string asset_hash = 5;</code>
   */
  com.google.protobuf.ByteString
      getAssetHashBytes();

  /**
   * <pre>
   * 资产状态
   * </pre>
   *
   * <code>uint32 status = 6;</code>
   */
  int getStatus();

  /**
   * <pre>
   * 资产创建时间, Unix 时间
   * </pre>
   *
   * <code>uint64 create_time = 7;</code>
   */
  long getCreateTime();
}
