// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

public interface AssetTotalSupplyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.AssetTotalSupplyReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 资产总数量, 十进制字符串
   * </pre>
   *
   * <code>string total_supply = 1;</code>
   */
  java.lang.String getTotalSupply();
  /**
   * <pre>
   * 资产总数量, 十进制字符串
   * </pre>
   *
   * <code>string total_supply = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalSupplyBytes();
}
