// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

/**
 * Protobuf type {@code blockchain.AssetTotalSupplyReply}
 */
public  final class AssetTotalSupplyReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.AssetTotalSupplyReply)
    AssetTotalSupplyReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssetTotalSupplyReply.newBuilder() to construct.
  private AssetTotalSupplyReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssetTotalSupplyReply() {
    totalSupply_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AssetTotalSupplyReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            totalSupply_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetTotalSupplyReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetTotalSupplyReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.launch.diagdevice.blockchain.AssetTotalSupplyReply.class, com.launch.diagdevice.blockchain.AssetTotalSupplyReply.Builder.class);
  }

  public static final int TOTAL_SUPPLY_FIELD_NUMBER = 1;
  private volatile java.lang.Object totalSupply_;
  /**
   * <pre>
   * 资产总数量, 十进制字符串
   * </pre>
   *
   * <code>string total_supply = 1;</code>
   */
  public java.lang.String getTotalSupply() {
    java.lang.Object ref = totalSupply_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalSupply_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资产总数量, 十进制字符串
   * </pre>
   *
   * <code>string total_supply = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTotalSupplyBytes() {
    java.lang.Object ref = totalSupply_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalSupply_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTotalSupplyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, totalSupply_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTotalSupplyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, totalSupply_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.launch.diagdevice.blockchain.AssetTotalSupplyReply)) {
      return super.equals(obj);
    }
    com.launch.diagdevice.blockchain.AssetTotalSupplyReply other = (com.launch.diagdevice.blockchain.AssetTotalSupplyReply) obj;

    boolean result = true;
    result = result && getTotalSupply()
        .equals(other.getTotalSupply());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_SUPPLY_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSupply().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.launch.diagdevice.blockchain.AssetTotalSupplyReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.AssetTotalSupplyReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.AssetTotalSupplyReply)
      com.launch.diagdevice.blockchain.AssetTotalSupplyReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetTotalSupplyReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetTotalSupplyReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.launch.diagdevice.blockchain.AssetTotalSupplyReply.class, com.launch.diagdevice.blockchain.AssetTotalSupplyReply.Builder.class);
    }

    // Construct using com.launch.diagdevice.blockchain.AssetTotalSupplyReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      totalSupply_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.launch.diagdevice.blockchain.BlockChainProto.internal_static_blockchain_AssetTotalSupplyReply_descriptor;
    }

    public com.launch.diagdevice.blockchain.AssetTotalSupplyReply getDefaultInstanceForType() {
      return com.launch.diagdevice.blockchain.AssetTotalSupplyReply.getDefaultInstance();
    }

    public com.launch.diagdevice.blockchain.AssetTotalSupplyReply build() {
      com.launch.diagdevice.blockchain.AssetTotalSupplyReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.launch.diagdevice.blockchain.AssetTotalSupplyReply buildPartial() {
      com.launch.diagdevice.blockchain.AssetTotalSupplyReply result = new com.launch.diagdevice.blockchain.AssetTotalSupplyReply(this);
      result.totalSupply_ = totalSupply_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.launch.diagdevice.blockchain.AssetTotalSupplyReply) {
        return mergeFrom((com.launch.diagdevice.blockchain.AssetTotalSupplyReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.launch.diagdevice.blockchain.AssetTotalSupplyReply other) {
      if (other == com.launch.diagdevice.blockchain.AssetTotalSupplyReply.getDefaultInstance()) return this;
      if (!other.getTotalSupply().isEmpty()) {
        totalSupply_ = other.totalSupply_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.launch.diagdevice.blockchain.AssetTotalSupplyReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.launch.diagdevice.blockchain.AssetTotalSupplyReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object totalSupply_ = "";
    /**
     * <pre>
     * 资产总数量, 十进制字符串
     * </pre>
     *
     * <code>string total_supply = 1;</code>
     */
    public java.lang.String getTotalSupply() {
      java.lang.Object ref = totalSupply_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalSupply_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资产总数量, 十进制字符串
     * </pre>
     *
     * <code>string total_supply = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTotalSupplyBytes() {
      java.lang.Object ref = totalSupply_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalSupply_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资产总数量, 十进制字符串
     * </pre>
     *
     * <code>string total_supply = 1;</code>
     */
    public Builder setTotalSupply(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalSupply_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产总数量, 十进制字符串
     * </pre>
     *
     * <code>string total_supply = 1;</code>
     */
    public Builder clearTotalSupply() {
      
      totalSupply_ = getDefaultInstance().getTotalSupply();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资产总数量, 十进制字符串
     * </pre>
     *
     * <code>string total_supply = 1;</code>
     */
    public Builder setTotalSupplyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalSupply_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.AssetTotalSupplyReply)
  }

  // @@protoc_insertion_point(class_scope:blockchain.AssetTotalSupplyReply)
  private static final com.launch.diagdevice.blockchain.AssetTotalSupplyReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.launch.diagdevice.blockchain.AssetTotalSupplyReply();
  }

  public static com.launch.diagdevice.blockchain.AssetTotalSupplyReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetTotalSupplyReply>
      PARSER = new com.google.protobuf.AbstractParser<AssetTotalSupplyReply>() {
    public AssetTotalSupplyReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AssetTotalSupplyReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AssetTotalSupplyReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetTotalSupplyReply> getParserForType() {
    return PARSER;
  }

  public com.launch.diagdevice.blockchain.AssetTotalSupplyReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

