// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

public final class BlockChainProto {
  private BlockChainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_TransactionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_TransactionReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_CreateAssetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_CreateAssetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssignAssetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssignAssetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_UpdateAssetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_UpdateAssetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AppendRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AppendRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssetTotalSupplyReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssetTotalSupplyReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssetRecordOfRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssetRecordOfRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssetRecordCountReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssetRecordCountReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssetRecordOfReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssetRecordOfReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_AssetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_AssetReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blockchain_SendToAddrRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blockchain_SendToAddrRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020blockchain.proto\022\nblockchain\"\032\n\007Reques" +
      "t\022\017\n\007api_key\030\001 \001(\t\"$\n\020TransactionReply\022\020" +
      "\n\010txn_hash\030\001 \001(\t\"v\n\022CreateAssetRequest\022\017" +
      "\n\007api_key\030\001 \001(\t\022\020\n\010asset_id\030\002 \001(\t\022\022\n\nass" +
      "et_name\030\003 \001(\t\022\025\n\rasset_content\030\004 \001(\t\022\022\n\n" +
      "asset_hash\030\005 \001(\t\"\213\001\n\022AssignAssetRequest\022" +
      "\017\n\007api_key\030\001 \001(\t\022\023\n\013asset_owner\030\002 \001(\t\022\020\n" +
      "\010asset_id\030\003 \001(\t\022\022\n\nasset_name\030\004 \001(\t\022\025\n\ra" +
      "sset_content\030\005 \001(\t\022\022\n\nasset_hash\030\006 \001(\t\"v" +
      "\n\022UpdateAssetRequest\022\017\n\007api_key\030\001 \001(\t\022\020\n" +
      "\010asset_id\030\002 \001(\t\022\022\n\nasset_name\030\003 \001(\t\022\025\n\ra" +
      "sset_content\030\004 \001(\t\022\022\n\nasset_hash\030\005 \001(\t\"q" +
      "\n\023AppendRecordRequest\022\017\n\007api_key\030\001 \001(\t\022\020" +
      "\n\010asset_id\030\002 \001(\t\022\023\n\013record_name\030\003 \001(\t\022\017\n" +
      "\007content\030\004 \001(\t\022\021\n\tmeta_hash\030\005 \001(\t\"-\n\025Ass" +
      "etTotalSupplyReply\022\024\n\014total_supply\030\001 \001(\t" +
      "\"1\n\014AssetRequest\022\017\n\007api_key\030\001 \001(\t\022\020\n\010ass" +
      "et_id\030\002 \001(\t\"L\n\024AssetRecordOfRequest\022\017\n\007a" +
      "pi_key\030\001 \001(\t\022\020\n\010asset_id\030\002 \001(\t\022\021\n\tmeta_h" +
      "ash\030\003 \001(\t\"-\n\025AssetRecordCountReply\022\024\n\014re" +
      "cord_count\030\001 \001(\t\"b\n\022AssetRecordOfReply\022\023" +
      "\n\013record_name\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\021\n\t" +
      "meta_hash\030\003 \001(\t\022\023\n\013update_time\030\004 \001(\004\"\231\001\n" +
      "\nAssetReply\022\025\n\raddress_owner\030\001 \001(\t\022\020\n\010as" +
      "set_id\030\002 \001(\t\022\022\n\nasset_name\030\003 \001(\t\022\025\n\rasse" +
      "t_content\030\004 \001(\t\022\022\n\nasset_hash\030\005 \001(\t\022\016\n\006s" +
      "tatus\030\006 \001(\r\022\023\n\013create_time\030\007 \001(\004\"A\n\021Send" +
      "ToAddrRequest\022\017\n\007api_key\030\001 \001(\t\022\014\n\004addr\030\002" +
      " \001(\t\022\r\n\005value\030\003 \001(\t2\300\005\n\004User\022M\n\013CreateAs" +
      "set\022\036.blockchain.CreateAssetRequest\032\034.bl" +
      "ockchain.TransactionReply\"\000\022M\n\013AssignAss" +
      "et\022\036.blockchain.AssignAssetRequest\032\034.blo" +
      "ckchain.TransactionReply\"\000\022G\n\013UpdateAsse" +
      "t\022\036.blockchain.UpdateAssetRequest\032\026.bloc" +
      "kchain.AssetReply\"\000\022O\n\014AppendRecord\022\037.bl" +
      "ockchain.AppendRecordRequest\032\034.blockchai" +
      "n.TransactionReply\"\000\022L\n\020AssetTotalSupply" +
      "\022\023.blockchain.Request\032!.blockchain.Asset" +
      "TotalSupplyReply\"\000\022=\n\007AssetOf\022\030.blockcha" +
      "in.AssetRequest\032\026.blockchain.AssetReply\"" +
      "\000\022Q\n\020AssetRecordCount\022\030.blockchain.Asset" +
      "Request\032!.blockchain.AssetRecordCountRep" +
      "ly\"\000\022S\n\rAssetRecordOf\022 .blockchain.Asset" +
      "RecordOfRequest\032\036.blockchain.AssetRecord" +
      "OfReply\"\000\022K\n\nSendToAddr\022\035.blockchain.Sen" +
      "dToAddrRequest\032\034.blockchain.TransactionR" +
      "eply\"\000B5\n com.launch.diagdevice.blockcha" +
      "inB\017BlockChainProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_blockchain_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blockchain_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_Request_descriptor,
        new java.lang.String[] { "ApiKey", });
    internal_static_blockchain_TransactionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_blockchain_TransactionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_TransactionReply_descriptor,
        new java.lang.String[] { "TxnHash", });
    internal_static_blockchain_CreateAssetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_blockchain_CreateAssetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_CreateAssetRequest_descriptor,
        new java.lang.String[] { "ApiKey", "AssetId", "AssetName", "AssetContent", "AssetHash", });
    internal_static_blockchain_AssignAssetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_blockchain_AssignAssetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssignAssetRequest_descriptor,
        new java.lang.String[] { "ApiKey", "AssetOwner", "AssetId", "AssetName", "AssetContent", "AssetHash", });
    internal_static_blockchain_UpdateAssetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_blockchain_UpdateAssetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_UpdateAssetRequest_descriptor,
        new java.lang.String[] { "ApiKey", "AssetId", "AssetName", "AssetContent", "AssetHash", });
    internal_static_blockchain_AppendRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_blockchain_AppendRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AppendRecordRequest_descriptor,
        new java.lang.String[] { "ApiKey", "AssetId", "RecordName", "Content", "MetaHash", });
    internal_static_blockchain_AssetTotalSupplyReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_blockchain_AssetTotalSupplyReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssetTotalSupplyReply_descriptor,
        new java.lang.String[] { "TotalSupply", });
    internal_static_blockchain_AssetRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_blockchain_AssetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssetRequest_descriptor,
        new java.lang.String[] { "ApiKey", "AssetId", });
    internal_static_blockchain_AssetRecordOfRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_blockchain_AssetRecordOfRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssetRecordOfRequest_descriptor,
        new java.lang.String[] { "ApiKey", "AssetId", "MetaHash", });
    internal_static_blockchain_AssetRecordCountReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_blockchain_AssetRecordCountReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssetRecordCountReply_descriptor,
        new java.lang.String[] { "RecordCount", });
    internal_static_blockchain_AssetRecordOfReply_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_blockchain_AssetRecordOfReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssetRecordOfReply_descriptor,
        new java.lang.String[] { "RecordName", "Content", "MetaHash", "UpdateTime", });
    internal_static_blockchain_AssetReply_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_blockchain_AssetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_AssetReply_descriptor,
        new java.lang.String[] { "AddressOwner", "AssetId", "AssetName", "AssetContent", "AssetHash", "Status", "CreateTime", });
    internal_static_blockchain_SendToAddrRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_blockchain_SendToAddrRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blockchain_SendToAddrRequest_descriptor,
        new java.lang.String[] { "ApiKey", "Addr", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
