// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package com.launch.diagdevice.blockchain;

public interface TransactionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.TransactionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 交易哈希
   * </pre>
   *
   * <code>string txn_hash = 1;</code>
   */
  java.lang.String getTxnHash();
  /**
   * <pre>
   * 交易哈希
   * </pre>
   *
   * <code>string txn_hash = 1;</code>
   */
  com.google.protobuf.ByteString
      getTxnHashBytes();
}
