spring:
  application:
    name: mycar-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRAP_ROOT_VALUE: false
      INDENT_OUTPUT: true
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    druid:
      url: jdbc:oracle:thin:@mycar.cn.db:1521:mycar
      username: mycar
      password: LAklwIhQvbxg17KMv9aNb9zL323Us30ClQXIQWrw34tpDnRG9qrUkOpJaIwYAwoaMTWN836Kv4Q+BKLC/L3xlw==
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK8rDCba6fcMtN8pMG+OQmIsW2Mqi4EDC7h2A1h4z0cudepWQo3I/aJr6rEIcTnjBqXXXgMMxx2u73zHus2qJUMCAwEAAQ==
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,config
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publickey}
  cache:
    type: REDIS
    redis:
      time-to-live: 3600000
  redis:
    host: 172.19.110.134
    port: 6379
    password: Launch123
    database: 0
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1000ms
      shutdown-timeout: 100ms
    timeout: 3000
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
dubbo:
  application:
    id: system-provide
    name: system-provide
  provider:
    timeout: 50000
  registry:
    address: zookeeper-01:2181,zookeeper-02:2182,zookeeper-03:2183
    protocol: zookeeper
    check: false
  protocol:
    port: 20885
    name: dubbo
    id: dubbo
    status: server
  scan:
    basePackages: com.launch.diagdevice.system.service
logging:
  path: /usr/local/diagdevice/logs
  file: /usr/local/diagdevice/logs/diagdevice-mycar-service.log
  level:
    root: info
    com: info